name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Set zipalign path
      run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check project
      run: ./gradlew check

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Align APK
      run: zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/ZofflineObb.apk

    - name: Download keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

    - name: Sign APK
      run: |
        apksigner sign --ks keystore.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --ks-pass ${{ secrets.KEYSTORE_PASSWORD }} app/build/outputs/apk/release/ZofflineObb.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ZofflineObb
        path: app/build/outputs/apk/release/ZofflineObb.apk
